notifications:
  email: false

env:
  - ELECTRON_CACHE=$HOME/.cache/electron

os:
  - osx
#  - linux
language: node_js
node_js: "8"

cache:
  directories:
    - node_modules
    - app/node_modules
    - tests/node_modules
    - $HOME/.cache/electron

install:
  - npm install
  - npm run rebuild
  - cd ./tests/
  - npm install
  - cd ..

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start && sleep 3;
    fi

script:
  - cd ./tests/
  - npm test
  - cd ..
  - if [ ! -z "$TRAVIS_TAG" ]; then npm run release; fi


#deploy:
#  provider: releases
#  api_key:
#    secure: paste your own api key here
#    - dist/*.AppImage
#    - dist/*.dmg
#    - dist/*.zip
#    - dist/*.exe
#  file_glob: true
#  skip_cleanup: true
#  on:
#    repo: broxme/brox-browser
#    tags: true
